#!/usr/bin/env python3
"""Vendor OPTIBubble's runtime Python deps as Flatpak wheel `sources`.

Flatpak runs *build-commands* in a network-isolated sandbox, so a naive
`pip install -r requirements.txt` fails there. The Flathub-standard fix is to
fetch every dependency as a wheel during the **source-download** phase (where
network is allowed) and install them with `--no-index` inside the sandbox.

This script resolves the exact closure for the freedesktop 24.08 SDK/runtime
(CPython 3.12 on a modern manylinux — the runtime's glibc >= 2.17 satisfies the
"manylinux_2_17 / 2_28" wheels pip picks) and writes a ready-to-embed YAML list
of `type: file` sources pointing at the canonical PyPI URLs with SHA-256 digests.

It shell out to pip to resolve (so markers and `python_requires` are honoured
exactly), then reconstructs each wheel's project/version from its filename using
PyPI name normalisation, and pulls the authoritative download URL + hash from
the PyPI JSON API.

Usage
-----
    python3 tools/flatpak_deps.py              # write packaging/flatpak/python-deps.yml
    python3 tools/flatpak_deps.py --check      # verify the emitted file parses

Splice the emitted `sources:` list into the `python3-deps` module of
com.optibubble.app.yml, and re-run this whenever requirements.txt changes.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
import tempfile
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REQS = ROOT / "requirements.txt"
OUT = ROOT / "packaging" / "flatpak" / "python-deps.yml"

PY = "3.12"


def _json(url: str, timeout: int = 40) -> dict:
    with urllib.request.urlopen(url, timeout=timeout) as r:
        return json.load(r)


def _normalise(name: str) -> str:
    """PyPI canonical name: lowercase, runs of `-_.` collapse to `-`."""
    return re.sub(r"[-_.]+", "-", name.lower()).strip("-")


def _pip_resolve() -> list[Path]:
    """Download the cp312 manylinux closure into a temp dir; return wheel paths."""
    tmp = Path(tempfile.mkdtemp(prefix="obwheels-"))
    cmd = [
        sys.executable, "-m", "pip", "download", "-r", str(REQS),
        "--only-binary=:all:",
        "--python-version", PY, "--implementation", "cp", "--abi", "cp312",
        "-d", str(tmp),
    ]
    # Do not pass --platform: letting pip use the host means it applies normal
    # manylinux compatibility and will accept the manylinux_2_17 AND 2_28 wheels
    # the freedesktop runtime needs.
    subprocess.run(cmd, check=True)
    return sorted(tmp.glob("*.whl"))


def _wheel_url_and_hash(fname: str) -> tuple[str, str]:
    """Given a wheel filename, return (url, sha256) from PyPI's JSON API."""
    # name-version from the first two hyphen-separated segments.
    parts = fname.split("-")
    name = _normalise(parts[0])
    version = parts[1]
    d = _json(f"https://pypi.org/pypi/{name}/{version}/json")
    for f in d["urls"]:
        if f["filename"] == fname:
            return f["url"], f["digests"]["sha256"]
    raise RuntimeError(f"no PyPI listing for {fname}")


def _emit(rows: list[tuple[str, str]]) -> str:
    lines = ["# Auto-generated by tools/flatpak_deps.py — DO NOT EDIT.",
             "# Vendored wheels for the python3-deps module (com.optibubble.app.yml).",
             "# Each wheel is fetched at prep time, installed offline with --no-index.",
             "sources:"]
    for url, sha in rows:
        lines.append("  - type: file")
        lines.append(f"    url: {url}")
        lines.append(f"    sha256: {sha}")
        lines.append("    dest: wheels")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    if args.check:
        if not OUT.exists():
            print(f"{OUT} missing — run: python3 tools/flatpak_deps.py")
            return 1
        n = OUT.read_text().count("url: ")
        print(f"{OUT}: {n} vendored wheel source(s) ✔")
        return 0

    wheels = _pip_resolve()
    print(f"pip resolved {len(wheels)} wheels:")
    rows = []
    for w in wheels:
        url, sha = _wheel_url_and_hash(w.name)
        # trust the downloaded file's digest over the listing to catch drift
        local = hashlib.sha256(w.read_bytes()).hexdigest()
        if local != sha:
            print(f"  ! digest mismatch for {w.name} (listing vs file)", file=sys.stderr)
            sha = local
        print(f"  {w.name}")
        rows.append((url, sha))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(_emit(rows))
    print(f"\nwrote {OUT} ({OUT.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
